config/routes.rb
Rails.application.routes.draw do
  # root page
  root to: 'pages#index'
  # cart page
  get 'cart', to:"carts#index", as: "cart"
  get 'carts/:id', to: "carts#show"
  delete 'carts/:id', to: "carts#destroy"
  # cartproducts (the product added to cart by the current user)
  post 'cart_products', to: "cart_products#create"
  delete 'cart_products/:id', to: "cart_products#destroy", as: "remove_product_from_cart" 
  # myShop page
  get 'pages/myshop', to: "pages#myshop", as: "myshop"
  #devise
  devise_for :users
  # products pages + show by sorts and categories
  resources :products
  get 'show_by_category/:id', to: "products#show_by_category", as: "category"
  get 'show_by_sort/:id', to: "products#show_by_sort", as: "sort"
  # order pages and success pages
  post 'products/:id/order', to: "products#place_order", as: "order"
  get 'myorder/success', to: "myorder#success", as: "order_success"
  get 'myorder', to: "myorder#myorder", as: "my_order"
  
  # place several orders together in cart page 
  post 'cart/place_orders', to: "carts#place_orders", as: "orders"
end

app/views/shared/_cart.html.erb
 <% if user_signed_in? %>
          <div id="cart" class="cart" data-totalitems="0">

              <%= link_to cart_path, class: "nav-link" do %>
            <%= fa_icon "shopping-cart" %>
            
            <% end %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
       
       
       

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">

    <%= link_to root_path, class: "nav-link", style:"color:#32CCCC" do %>
            <%= fa_icon "headphones" %>
            <%= "BandFleaMarket" %>
    <% end %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="position-sticky collapse navbar-collapse justify-content-end" id="navbarNav" style="justify-content:center">
          <% if user_signed_in? %>
            <%= link_to myshop_path, class: "nav-link", style:"color:#32CCCC" do %>
            <%= fa_icon "user" %>
            <%= "MyShop" %>
            <% end %>  
            <%= link_to cart_path, class: "nav-link", style:"color:#32CCCC" do %>
            <%= fa_icon "shopping-cart" %>
            <%= "MyCart" %>
            <% end %>
            <%= link_to my_order_path, class: "nav-link", style:"color:#32CCCC" do %>
            <%= fa_icon "list" %>
            <%= "MyOrder" %>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link", style:"color:#32CCCC" do %>
            <%= fa_icon "sign-out" %>
            <%= "Sign Out" %>
            <% end %>
            <% else %>
            <%= link_to new_user_session_path, class: "nav-link", style:"color:#32CCCC" do %>
            <%= fa_icon "user" %>
            <%= "Sign In" %>
            <% end %>
            <%= link_to new_user_registration_path, class: "nav-link", style:"color:#32CCCC" do %>
            <%= fa_icon "user" %>
            <%= "Sign Up" %>
            <% end %>
         <% end %>
    </div>
</nav>


<div class="dropdown">
        <div style="display:table-cell">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#32CCCC">
        Guitar&Bass
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "Guitar", sort_path(1), class:"dropdown-item" %>
        <%= link_to "Bass", sort_path(2), class:"dropdown-item" %>

        </div>
      </div>
    
    <div style="display:table-cell">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#32CCCC" >
          Pedals
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Overdrive", sort_path(3), class:"dropdown-item" %>
          <%= link_to "Distortion", sort_path(4), class:"dropdown-item" %>
          <%= link_to "Fuzz", sort_path(5), class:"dropdown-item" %>
          <%= link_to "Reverb", sort_path(6), class:"dropdown-item" %>
          <%= link_to "delay", sort_path(7), class:"dropdown-item" %>
          <%= link_to "Pitch", sort_path(8), class:"dropdown-item" %>
          <%= link_to "Octave", sort_path(9), class:"dropdown-item" %>
          <%= link_to "Tuner", sort_path(10), class:"dropdown-item" %>
          <%= link_to "EQ", sort_path(11), class:"dropdown-item" %>
          <%= link_to "Compressor", sort_path(12), class:"dropdown-item" %>
          <%= link_to "Flanger", sort_path(13), class:"dropdown-item" %>
          <%= link_to "Phaser", sort_path(14), class:"dropdown-item" %>
        </div>
      </div>

      <div style="display:table-cell">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#32CCCC" >
          Amplifier
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Acoustic", sort_path(15), class:"dropdown-item" %>
          <%= link_to "High Gain", sort_path(16), class:"dropdown-item" %>
        </div>
      </div>

      <div style="display:table-cell">
        <%= link_to "Others", sort_path(17), class:"nav-link", style:"color:#32CCCC" %>
      </div>
    
      <div style="display:table-cell">
        <%= link_to "Show All", products_path, class:"nav-link", style:"color:#32CCCC" %>
      </div>
</div>
      