config/routes.rb
Rails.application.routes.draw do
  # root page
  root to: 'pages#index'
  # cart page
  get 'cart', to:"carts#index", as: "cart"
  get 'carts/:id', to: "carts#show"
  delete 'carts/:id', to: "carts#destroy"
  # cartproducts (the product added to cart by the current user)
  post 'cart_products', to: "cart_products#create"
  delete 'cart_products/:id', to: "cart_products#destroy", as: "remove_product_from_cart" 
  # myShop page
  get 'pages/myshop', to: "pages#myshop", as: "myshop"
  #devise
  devise_for :users
  # products pages + show by sorts and categories
  resources :products
  get 'show_by_category/:id', to: "products#show_by_category", as: "category"
  get 'show_by_sort/:id', to: "products#show_by_sort", as: "sort"
  # order pages and success pages
  post 'products/:id/order', to: "products#place_order", as: "order"
  get 'myorder/success', to: "myorder#success", as: "order_success"
  get 'myorder', to: "myorder#myorder", as: "my_order"
  
  # place several orders together in cart page 
  post 'cart/place_orders', to: "carts#place_orders", as: "orders"
end

app/views/pages/index.html.erb
<div class="div-a">
      
        
            <div class="card-body">
                <h2>Looking for something...</h2>
                <br>
                <p class="card-text">Are you looking for something? Clicking the button here to see more!</p>
                <p class="card-text">As a Buyer</p>
                <br>
                <%= link_to "I'm looking for something...", products_path, style:"color:#32ffff;text-decoration: none;" %>

            </div>
        
            <div class="card-body" style="margin-top:20px;">
                <h2>Have something to sell...</h2>
                <p class="card-text">It's the time to add a new product in your own shop!</p>
                <p class="card-text">As a seller</p>
                <br>

                <%= link_to "I have something to sell...", new_product_path, style:"color:#32ffff;text-decoration: none;" %>

            </div>
        
   
</div>



<div class="big-div">
    <div class="container mt-3 c1" >
       
            <div class="card-body">
                <h1>Guitar & Bass</h1>
                <br>
                <br>
                <br>
                <br>
                <%= link_to "Guitar & Bass", category_path(1), style:"color:#32ffff;text-decoration: none;" %>

            </div>
        
    </div>

    <div class="container mt-3 c2" > 
       
            <div class="card-body">
                <h1>Pedals</h1>
                <br>
                <br>
                <br>
                <br>
                <%= link_to "Pedals", category_path(2), style:"color:#32ffff;text-decoration: none;" %>

            </div>
        
    </div>

    <div class="container mt-3 c3" >   
       
            <div class="card-body">
                <h1>Amplifier</h1>
                <br>
                <br>
                <br>
                <br>
                <%= link_to "Amplifier", category_path(3), style:"color:#32ffff;text-decoration: none;" %>

            </div>
        
    </div>

    <div class="container mt-3 c4" > 
        
            <div class="card-body">
                <h1>Others</h1>
                <br>
                <br>
                <br>
                <br>
                <%= link_to "Others", category_path(4), style:"color:#32ffff;text-decoration: none;" %>
            </div>
    </div>
</div>

app/views/pages/myshop.html.erb
<div class="reg" style="margin:0 auto;">

<h1>myShop</h1>
<%= link_to 'I want to sell something', new_product_path, style:"color:#32CCCC;font-size:1.2em;" %>

<table style="margin:0 auto;">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th>Sold</th>
      <th>Price</th>
      <th>Category</th>
      <th>Sort</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<% Product.where(user_id: current_user.id).each do |product| %>
  <tbody>
      <tr>
        <td><%= image_tag(product.picture, height: "150") %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.user.username %></td>
        <% if product.sold == false %>
          <td>Not yet</td>
        <% else %>
          <td>Sold</td>
        <% end %>
        <td><%= product.price %></td>
        <td><%= product.category.category %></td>
        <td><%= product.sort.sort %></td>
        <td><%= link_to 'Show', product, style:"color:#32CCCC" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), style:"color:#32CCCC" %></td>
        <td><%= link_to 'Delete', product, style:"color:#32CCCC", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    
  </tbody>

<% end %>
</table>
</div>