config/routes.rb
Rails.application.routes.draw do
  # root page
  root to: 'pages#index'
  # cart page
  get 'cart', to:"carts#index", as: "cart"
  get 'carts/:id', to: "carts#show"
  delete 'carts/:id', to: "carts#destroy"
  # cartproducts (the product added to cart by the current user)
  post 'cart_products', to: "cart_products#create"
  delete 'cart_products/:id', to: "cart_products#destroy", as: "remove_product_from_cart" 
  # myShop page
  get 'pages/myshop', to: "pages#myshop", as: "myshop"
  #devise
  devise_for :users
  # products pages + show by sorts and categories
  resources :products
  get 'show_by_category/:id', to: "products#show_by_category", as: "category"
  get 'show_by_sort/:id', to: "products#show_by_sort", as: "sort"
  # order pages and success pages
  post 'products/:id/order', to: "products#place_order", as: "order"
  get 'myorder/success', to: "myorder#success", as: "order_success"
  get 'myorder', to: "myorder#myorder", as: "my_order"
  
  # place several orders together in cart page 
  post 'cart/place_orders', to: "carts#place_orders", as: "orders"
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    
    has_many :products, through: :cart_products
end

app/controllers/carts_controller.rb
class CartsController < ProductsController
  before_action :current_cart
  before_action :set_product_in_cart

  def index

  end
  # place orders together in cart page
  def place_orders
    @cartproducts.each do |pc|
      buy_product = Product.find_by(id: pc.product_id)
      Order.create(
        product_id: pc.product_id,
        buyer_id: current_user.id,
        seller_id: buy_product.user_id
      )
      buy_product.sold = true
      buy_product.save
    end
    redirect_to order_success_path
  end

  private
  # make sure the cart is connected with the current user
  def current_cart
    if session[:cart_id] != nil
      cart = Cart.find_by(user_id: current_user.id)
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end
    if session[:cart_id] == nil
      @current_cart = Cart.create(user_id: current_user.id)
      session[:cart_id] = @current_cart.id
    end
  end

  def cart_params
    params.require(:cart).permit(:product_id, :buyer_id, :seller_id)
  end

  def set_product_in_cart
    @cartproducts = CartProduct.where(cart_id: @current_cart.id)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<div class="reg" style="margin:0 auto;">
<%# to check is there any products the current user add to their cart %>
<% if @cartproducts.find_by(cart_id: @current_cart) == nil %>
<p style="font-size:1.3em;">Your cart is empty.</p>
<%= link_to "Click Me and let's go shopping in BandFleaMarket", products_path, style:"color:#32ffff;font-size:1.5em;" %>
<% else %>
<table style="margin:0 auto;">
  <thead>
    <tr>
      <th style="text-align:center;">Picture</th>
      <th style="text-align:center;">Title</th>
      <th style="text-align:center;">User</th>
      <th style="text-align:center;">Price</th>
      <th style="text-align:center;">Category</th>
      <th style="text-align:center;">Sort</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%# set initial total price %>
<% total_price = 0 %>
<%# loop all the added products and show them in a table %>
<% @cartproducts.each do |cp| %>
<%# if the product is already sold after the user add it to the cart, the product will not appear in the cart %>
<% if Product.find_by(id: cp.product_id).sold == true %>
<% cp.delete %>
<% else %>
<% added_product = Product.find_by(id: cp.product_id) %>
    <tr>
      <td style="text-align:center;"><%= link_to image_tag(added_product.picture, height: "150"), added_product %>
      </td>
      <td style="text-align:center;"><%= link_to added_product.title, added_product, style:"color:#32ffff;" %></td>
      <td style="text-align:center;"><%= added_product.user.username %></td>
      <td style="text-align:center;"><%= added_product.price %></td>
      <td style="text-align:center;"><%= added_product.category.category %></td>
      <td style="text-align:center;"><%= added_product.sort.sort %></td>
      <td><%= link_to "Remove Product", remove_product_from_cart_path(cp), method: :delete %></td>
    </tr>
    <%# add the price together %>
    <% total_price += added_product.price %>
  <% end %>
<% end %>
  </tbody>
</table>
<br>
<p style="color:#32cccc;">
<%= "Total cost: $#{total_price}" %>
</p>
<%# pay together and create orders for each product %>
<%= button_to "Pay Together", orders_path, style:"color:#32CCCC" %>
<% end %>
</div>