config/routes.rb
Rails.application.routes.draw do
  # root page
  root to: 'pages#index'
  # cart page
  get 'cart', to:"carts#index", as: "cart"
  get 'carts/:id', to: "carts#show"
  delete 'carts/:id', to: "carts#destroy"
  # cartproducts (the product added to cart by the current user)
  post 'cart_products', to: "cart_products#create"
  delete 'cart_products/:id', to: "cart_products#destroy", as: "remove_product_from_cart" 
  # myShop page
  get 'pages/myshop', to: "pages#myshop", as: "myshop"
  #devise
  devise_for :users
  # products pages + show by sorts and categories
  resources :products
  get 'show_by_category/:id', to: "products#show_by_category", as: "category"
  get 'show_by_sort/:id', to: "products#show_by_sort", as: "sort"
  # order pages and success pages
  post 'products/:id/order', to: "products#place_order", as: "order"
  get 'myorder/success', to: "myorder#success", as: "order_success"
  get 'myorder', to: "myorder#myorder", as: "my_order"
  
  # place several orders together in cart page 
  post 'cart/place_orders', to: "carts#place_orders", as: "orders"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :sort
  has_rich_text :description
  has_one_attached :picture
  has_many :cart_products
  def newsizeimage
    return self.picture.variant(resize: "300x300")
  end
end

app/controllers/products_controller.rb
class ProductsController < CartProductsController
  
  before_action :set_product, only: %i[ show edit update destroy place_order ]
  before_action :set_page, only: %i[ index show_by_sort show_by_category ]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :show_by_sort, :show_by_category ]
  before_action :set_form_vars
  before_action :current_cart, except: %i[ index show_by_sort show_by_category show  ]
  # GET /products or /products.json

  # set the limited number of products shown in each page
  NUMBER_PRODUCTS_PER_PAGE = 5
  def index
    @products = Product.all
    # let each page only show 5 products
    @products_per_page = Product.offset(@page * NUMBER_PRODUCTS_PER_PAGE).limit(NUMBER_PRODUCTS_PER_PAGE)
    # if the user signed in give the user his cart, so the user can add the product directly in this page
    if user_signed_in?
      current_cart
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product.category = @product.sort.category
  end


  # show the products under same sort
  def show_by_sort
    # find the sort params
    @find_sort = @sorts.find do |s|
      s[:id] == params[:id].to_i
    end
    # select the products of this sort
    @find_products_by_sort = Product.where(sort_id:@find_sort.id)
    @find_products_per_page = @find_products_by_sort.offset(@page * NUMBER_PRODUCTS_PER_PAGE).limit(NUMBER_PRODUCTS_PER_PAGE)
    # if the user signed in give the user his cart, so the user can add the product directly in this page
    if user_signed_in?
      current_cart
    end
  end

  # show the products under same category 
  def show_by_category
    @find_category = @categories.find do |c|
      c[:id] == params[:id].to_i
    end
    @find_products_by_category = Product.where(category_id: @find_category.id)
    @find_products_per_page = @find_products_by_category.offset(@page * NUMBER_PRODUCTS_PER_PAGE).limit(NUMBER_PRODUCTS_PER_PAGE)
    # if the user signed in give the user his cart, so the user can add the product directly in this page    
    if user_signed_in?
      current_cart
    end

  end
  
  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.category = @product.sort.category
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product.category = @product.sort.category
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  # place the order with product_id, buyer_id and seller_id
  def place_order
    Order.create(
      product_id: @product.id,
      buyer_id: current_user.id,
      seller_id: @product.user_id
    )
    # if the product is bought, the sold will become into true. Then other customers can't buy it again.
    @product.sold = true
    @product.save
    redirect_to order_success_path
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
  
    # set the initial page number
    def set_page    
      @page = params.fetch(:page, 0).to_i
    end

    # set the instance varables
    def set_form_vars
      @categories = Category.all
      @sorts = Sort.all
    end
    # authorize control
    def authorize_user
      if current_user.id != @product.user_id
        flash[:alert] = "You can't do that!"
        redirect_to products_path
      end
    end

    # let the cart connect with current user, when a user signed in. if it is the first time for a user to sign in, just create a new cart withi this user's id.
    def current_cart
      if session[:cart_id] != nil
        cart = Cart.find_by(user_id: current_user.id)
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end
      if session[:cart_id] == nil
        @current_cart = Cart.create(user_id: current_user.id)
        session[:cart_id] = @current_cart.id
      end
    end
    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :user_id, :sold, :price, :category_id, :picture, :sort_id)
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field" style="width:500px;margin:auto;">
    <%= form.label :description%>
  <div style="background-color:white">
      <%= form.rich_text_area :description, style:"display:fixed;color:black" %>
  </div>

  </div>


  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :sort_id %>
    <%= form.select :sort_id, @sorts.map {|c| [c.sort, c.id]} %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>
  
  <div class="actions">
    <%= form.submit style:"color:#32CCCC;" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="reg" style="margin: auto 40px;">
<h1>Editing Product</h1>
<%= render 'form', product: @product %>
<%= link_to 'Show', @product, style:"color:#32ffff" %> |
<%= link_to 'Back', products_path, style:"color:#32ffff" %>
</div>

app/views/products/index.html.erb
<div class="reg" style="margin:0 auto;">
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
<%= render 'shared/cart' %>
<% end %>



<table style="margin:0 auto;">
  <thead>
    <tr>
      <th style="text-align:center;">Picture</th>
      <th style="text-align:center;">Title</th>
      <th style="text-align:center;">Description</th>
      <th style="text-align:center;">Seller</th>
      <th style="text-align:center;">Sold</th>
      <th style="text-align:center;">Price</th>
      <th style="text-align:center;">Category</th>
      <th style="text-align:center;">Sort</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products_per_page.each do |product| %>
    <tr>
      <td style="text-align:center;text-decoration: none;"><%= link_to image_tag(product.picture, height: "150"), product %>
      </td>
      <td style="text-align:center;"><%= link_to product.title, product, style:"color:#32CCCC;text-decoration: none;" %></td>
      <td style="text-align:center;"><%= product.description %></td>
      <td style="text-align:center;"><%= product.user.username %></td>
      <%# check the sold situation of the product %>
      <% if product.sold == false %>
      <td style="text-align:center;">Not yet</td>
      <% else %>
      <td style="text-align:center;">Sold</td>
      <% end %>
      <td style="text-align:center;"><%= product.price %></td>
      <td style="text-align:center;"><%= product.category.category %></td>
      <td style="text-align:center;"><%= product.sort.sort %></td>
      <td>
      <% if !user_signed_in? %>
        <%= link_to "Sign in to buy", new_user_session_path, style:"color:#32CCCC;text-decoration: none;" %>
      <% end %>
        <% if user_signed_in? %>
          <%# check if the current user already add this product to their cart %>
          <% already_add_to_cart = CartProduct.find_by(cart_id: @current_cart.id, product_id: product.id) %>
          <% if already_add_to_cart == nil %>
            <%# check whether the product is sold %>
            <% if product.sold == true && current_user.id != product.user_id %>
                Already Sold
            <%# check the product is belong to currents user %>
            <% elsif current_user.id == product.user_id %>
                This is your product
            <% elsif current_user.id != product.user_id %>
                <div class="page-wrapper">
                  <%= button_to cart_products_path(:product_id => product.id), id:"addtocart", style:"color:#32CCCC;text-decoration: none;" do %>
                    <%= "Add to cart" %>
                    <span class="cart-item"></span>
                  <% end %>
                </div>
            <% end %>
          <% else  %>
            <% if product.sold == true %>
              Already Sold
            <% else %>
              Already Added To Cart
            <% end %>
          <% end %>
        <% end %>
      </td>
    </tr>


    <% end %>
  </tbody>
</table>

<br>
<% if @page > 0 %>
<%= link_to "Previous Page", products_path(page: @page - 1), style:"color:#32CCCC;text-decoration: none;" %>
<% end %>
<% if @page < @products.length / 5  %>
<%= link_to "Next Page", products_path(page: @page + 1), style:"color:#32CCCC;text-decoration: none;" %>
<% end %>

</div>

app/views/products/new.html.erb
<div class="reg" style="margin:auto 50px;">
<h1>Add A Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, style:"color:#32ffff;text-decoration: none;" %>
</div>

app/views/products/show.html.erb
<div class="reg" style="font-size:1.2em;">
<p id="notice" style="font-size: 1.4em;color:#32CCCC"><%= notice %></p>
<%= render 'shared/cart' %>


<%= image_tag(@product.newsizeimage)  %>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @product.sold %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.category %>
</p>
<p>
  <strong>Sort:</strong>
  <%= @product.sort.sort %>
</p>

<% if user_signed_in? %>
<%# check if the product is belong to current user and whether this product is sold %>
<% if @product.sold == false && current_user.id != @product.user_id %>
  <%= button_to 'Buy now', order_path, style:"color:#32CCCC;" %>
<% elsif current_user.id == @product.user_id %>
        <p style="color:#32cccc;font-size:1.3em;">
        You can't buy product belongs to you.
        </p> 
<% else %>
  <p>SOLD</p>
<% end %>
<% else %>
<%= link_to "Sign in to buy", new_user_session_path, style:"color:#32CCCC;text-decoration: none;" %>
<% end %>

<br>


<%= link_to 'Back', products_path, style:"text-decoration: none;font-size:1.4em;color:#32CCCC;" %>

</div>

app/views/products/show_by_category.html.erb
<% if user_signed_in? %>
<%= render 'shared/cart' %>
<% end %>
<div class="reg" style="margin:0 auto;">


<table style="margin:0 auto;">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Title</th>
      <th>Description</th>
      <th>Seller</th>
      <th>Sold</th>
      <th>Price</th>
      <th>Category</th>
      <th>Sort</th>
      <th></th>

    </tr>
  </thead>
<%# select one category and show all the products belongs to this category %>
  <tbody>
    <% @find_products_per_page.each do |product| %>
    <tr>
      <td style="text-align:center;text-decoration: none;"><%= link_to image_tag(product.picture, height: "150"), product %>
        <br></td>
      <td><%= link_to product.title, product, style:"color:#fff;text-decoration: none;color:#32CCCC;" %></td>
      <td><%= product.description %></td>
      <td><%= product.user.username %></td>
      <% if product.sold == false %>
      <td>Not yet</td>
      <% else %>
      <td>Sold</td>
      <% end %>
      <td><%= product.price %></td>
      <td><%= product.category.category %></td>
      <td><%= product.sort.sort %></td>
<td>
        <% if !user_signed_in? %>
        <%= link_to "Sign in to buy", new_user_session_path, style:"color:#32CCCC;text-decoration: none;" %>
        <% end %>

        
        <% if user_signed_in? %>
        <% already_add_to_cart = CartProduct.find_by(cart_id: @current_cart.id, product_id: product.id) %>
        <% if already_add_to_cart == nil %>
        <% if product.sold == true && current_user.id != product.user_id %>
        Already Sold
        <% elsif current_user.id == product.user_id %>
        This is your product
        <% else %>
        <div class="page-wrapper">
          <%= button_to cart_products_path(:product_id => product.id), id:"addtocart", style:"color:#32CCCC;text-decoration: none;" do %>
          <%= "Add to cart" %>
          <span class="cart-item"></span>
          <% end %>
        
        </div>
        <% end %>
        <% else %>
        Already Added To Cart
        <% end %>
        <% end %>
      </td>
    </tr>

    <% end %>
  </tbody>
</table>

<br>
<% if @page > 0 %>
<%= link_to "Previous Page", products_path(page: @page - 1), style:"color:#32CCCC;text-decoration: none;" %>
<% end %>
<% if @page < @find_products_by_category.length / 5  %>
<%= link_to "Next Page", products_path(page: @page + 1), style:"color:#32CCCC;text-decoration: none;" %>
<% end %>


</div>

app/views/products/show_by_sort.html.erb
<% if user_signed_in? %>
<%= render 'shared/cart' %>
<% end %>

<div style="margin:0 auto;">


<table style="margin:0 auto;">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Title</th>
      <th>Description</th>
      <th>Seller</th>
      <th>Sold</th>
      <th>Price</th>
      <th>Category</th>
      <th>Sort</th>
      <th></th>

    </tr>
  </thead>
<%# select one sort and show all the products belongs to this category %>
  <tbody>
    <% @find_products_per_page.each do |product| %>

    <tr>
      <td style="text-align:center;text-decoration: none;"><%= link_to image_tag(product.picture, height: "150"), product %>
        <br></td>
      <td><%= link_to product.title, product, style:"color:#32CCCC;text-decoration: none;" %></td>
      <td><%= product.description %></td>
      <td><%= product.user.username %></td>
      <% if product.sold == false %>
      <td>Not yet</td>
      <% else %>
      <td>Sold</td>
      <% end %>
      <td><%= product.price %></td>
      <td><%= product.category.category %></td>
      <td><%= product.sort.sort %></td>
<td>
        <% if !user_signed_in? %>
        <%= link_to "Sign in to buy", new_user_session_path, style:"color:#32CCCC;text-decoration: none;" %>
        <% end %>

        
        <% if user_signed_in? %>
        <% already_add_to_cart = CartProduct.find_by(cart_id: @current_cart.id, product_id: product.id) %>
        <% if already_add_to_cart == nil %>
        <% if product.sold == true && current_user.id != product.user_id %>
        Already Sold
        <% elsif current_user.id == product.user_id %>
        This is your product
        <% else %>
        <div class="page-wrapper">
          <%= button_to cart_products_path(:product_id => product.id), id:"addtocart", style:"color:#32CCCC;text-decoration: none;" do %>
          <%= "Add to cart" %>
          <span class="cart-item"></span>
          <% end %>
        
        </div>
        <% end %>
        <% else %>
        Already Added To Cart
        <% end %>
        <% end %>
      </td>
    </tr>

    <% end %>
  </tbody>
</table>

<br>
<% if @page > 0 %>
<%= link_to "Previous Page", products_path(page: @page - 1), style:"color:#32CCCC;text-decoration: none;" %>
<% end %>
<% if @page < @find_products_by_sort.length / 5  %>
<%= link_to "Next Page", products_path(page: @page + 1), style:"color:#32CCCC;text-decoration: none;" %>
<% end %>

</div>